Hw04 auth
AnnaKhanina/nodejs-homework-restApi pull request #3
Opened 2022-11-18 12:28 UTC by AnnaKhanina

2022-11-18 19:54 UTC, Eastvarga commented on models/users.js
> +    process.env.JWT_SECRET
Зазвичай подібні змінні виводять до окремого файлу config якмий імпортують туди де треба використовувати ці змінні

2022-11-18 19:55 UTC, Eastvarga commented on models/users.js
> +    process.env.JWT_SECRET
Зазвичай подібні змінні виводять до окремого файлу config якмий імпортують туди де треба використовувати ці змінні

2022-11-18 19:55 UTC, Eastvarga commented on models/users.js
> +    process.env.JWT_SECRET
Зазвичай подібні змінні виводять до окремого файлу config якмий імпортують туди де треба використовувати ці змінні

2022-11-18 20:18 UTC, Eastvarga commented on routes/api/users.js
> +  singup,
Не вірне ім'я функції, перевірте написання.

2022-11-18 20:20 UTC, Eastvarga commented on routes/api/users.js
> +router.post("/singup", loginValidation, tryCatchWrapper(singup));
singup? Ви впевнені що код працює

2022-11-18 20:20 UTC, Eastvarga requested changes
Є зауваження

2022-11-19 11:37 UTC, AnnaKhanina commented on routes/api/users.js
> +  singup,
Дякую

2022-11-19 11:49 UTC, AnnaKhanina commented on routes/api/users.js
> +router.post("/singup", loginValidation, tryCatchWrapper(singup));
виправила

2022-11-19 18:39 UTC, Eastvarga commented on controllers/contactsController.js
>      if (Object.keys(req.body).length === 0) {
Навіщо валідувати те що Ви вже валідували? Начебто схема валідації потребує існування поля favorite, тоб-то цей код ніколи не виконається

2022-11-19 18:40 UTC, Eastvarga commented on models/contacts.js
> +  console.log(favorite);
не потрібно у робочому коді залишати консолі

2022-11-19 19:20 UTC, Eastvarga commented on models/contacts.js
> +  await Contact.findOneAndUpdate( { $and: [{ owner }, { _id: contactId }] }, { $set: body }, { runValidators: true });
А що повертає цей метод? невже не можна обійтись без використання строки коду що йде нижче?

2022-11-19 19:23 UTC, Eastvarga commented on routes/api/users.js
> +router.get("/logout", tryCatchWrapper(logoutMiddleware));
Не коректне використання мидлвара. Мидлвар не є контроллером або сервісов який виконує основну логіку раута, це обробка додаткова, нашарювання навколо основного сервісу. А у Вас вийшла дуже дивна конструкція. До тогож треба було використати мідлвар авторізації а у сомому логіні просто обнулити токен у юзера. Десь Ви поспішали та погано вивчали матеріал

2022-11-19 19:24 UTC, Eastvarga requested changes
Є зауваження

2022-11-20 07:30 UTC, AnnaKhanina commented on models/contacts.js
> +  console.log(favorite);
виправила

2022-11-20 07:30 UTC, AnnaKhanina commented on models/contacts.js
> +  await Contact.findOneAndUpdate( { $and: [{ owner }, { _id: contactId }] }, { $set: body }, { runValidators: true });
виправила

2022-11-20 08:29 UTC, AnnaKhanina commented on routes/api/users.js
> +router.get("/logout", tryCatchWrapper(logoutMiddleware));
виправила

2022-11-22 15:28 UTC, Eastvarga approved these changes
Є багато недоліків, котрі треба доопрацювати

2022-11-22 15:32 UTC, Eastvarga commented
Відаліть Надю з ревьюверів та можете мержити реквест

2022-11-23 08:45 UTC, merged