Hw06 email
AnnaKhanina/nodejs-homework-restApi pull request #5
Opened 2022-12-10 15:16 UTC by AnnaKhanina

Добрий вечір! Перевірте, будь ласка.

2022-12-10 15:47 UTC, Eastvarga requested changes
Є зауваження

2022-12-10 15:47 UTC, Eastvarga commented on models/users.js
> +  if (user.verify) {
Останній if зайвий, бо це єдиний варіант залишиться якщо попередні if не спрацюють
Можна просто залишити 
 return res.json({
      message: "Your Email already verified",
    });
без блок скоупу   if (user.verify){ }

2022-12-10 15:47 UTC, Eastvarga commented on models/users.js
> +  if (!email) {
Не вірна послідовність перевірки та запиту знайти юзера по пошті
Ви спочатку шукаєте юзера по пошті, а потім перевіряєте чи пошта існує взагалі, це дивно.

2022-12-10 15:47 UTC, Eastvarga commented on models/users.js
> +  if (!user.verify) {
Теж саме, зайвий скоуп if (!user.verify) { }
бо це єдиний варіант що залишиться, якщо інші  if не спрацюють, бо інші кидають помилку, а помилка припиняє виконання подальшого коду у поточному скоупі, та перехоплюється та хендлиться.
залишиться просто:
await sendRegisterEmail({ email, verificationToken });
    res.status(200).json({ message: "Verification email sent" });

2022-12-11 08:22 UTC, AnnaKhanina commented on models/users.js
> +  if (user.verify) {
+

2022-12-11 08:23 UTC, AnnaKhanina commented on models/users.js
> +  if (!email) {
виправлено

2022-12-11 08:23 UTC, AnnaKhanina commented on models/users.js
> +  if (!user.verify) {
прибрала

2022-12-11 12:44 UTC, Eastvarga requested changes

2022-12-11 12:44 UTC, Eastvarga commented on models/users.js
>    const user = await User.findOne({ email });
if (!email) {
    res.status(400).json({ message: "missing required field email" });
  }
треба робити до запиту
const user = await User.findOne({ email });
Тому що немає сенсу в тому щоб шукати юзера по пошті якої не існує

2022-12-11 16:08 UTC, Eastvarga approved these changes

2022-12-11 16:08 UTC, merged